#!/bin/bash

BI=/home/killer/demo/BillingSystem/master/bill_items.txt
PD=/home/killer/demo/BillingSystem/master/products.txt

    echo "-----------------------------"
    cat $PD
    echo "-----------------------------"

# Order Function
Your_order() {

    total=0
    bill_id=$(date "+%Y-%m-%d %H:%M")

    while true
    do
        read -p "Enter Product ID (0 to Bill): " pid

        if [ "$pid" -eq 0 ]; then

        echo "Enter Customer Details"

    read -p "Customer Name: " cname
    read -p "Customer Mobile: " cmobile

    echo "$bill_id|$cname|$cmobile|$name|$qty|$amount" >> $BI

    echo "Added -> $name * $qty = Rs.$amount"
    echo ""
    echo "Thank You"

  break
        fi

        product=$(grep "^$pid|" $PD)

        if [ -z "$product" ]; then
            echo "Invalid Product ID!"
            continue
        fi

        name=$(echo "$product" | cut -d'|' -f2 | xargs)
        price=$(echo "$product" | cut -d'|' -f3 | xargs)
        stock=$(echo "$product" | cut -d'|' -f4 | xargs)

        read -p "Enter Quantity: " qty

        if [ "$qty" -gt "$stock" ]; then
            echo "Stock not available!"
            continue
        fi

        new_stock=$((stock - qty))
        amount=$((price * qty))
        total=$((total + amount))

        # Update stock
        sed -i "s/^$pid|$name|$price|$stock/$pid|$name|$price|$new_stock/" $PD

    done
}

# Total Bill

Total_Bill() {

echo "Added -> $name * $qty = Rs.$amount"

    echo "------ BILL HISTORY ------"

    cat $BI
}

# Main Menu
while true
do
    echo ""
    echo "========= TEA SHOP ========="
    echo "1. Your Order"
    echo "2. Total Bill"
    echo "3. Exit"
    echo "============================"

    read -p "Choose Option: " choice

    case $choice in
        1) Your_order ;;
        2) Total_Bill ;;
        3) exit ;;
        *) echo "Invalid Option!" ;;
    esac
done
